export const section1 = [
  {
    question_id: 1662403538119,
    es: "¿Su institución ofrece contenidos educativos relacionados con BIM dentro de sus programas?",
    default:
      "Does your institution offer BIM-related educational content within its programmes?",
    answers: ["Yes", "No", "Not sure"],
  },
  {
    question_id: 1665076540133,
    es: "¿Qué programa académico ofrecido por su institución incluye contenidos educativos relacionados con BIM?",
    default:
      "Which academic programme offered by your institution include BIM-related educational content?",
  },
  {
    question_id: 1662403538116,
    es: "¿En qué nivel o niveles se ofrecen contenidos educativos relacionados con BIM dentro del programa académico identificado?",
    default:
      "At what level(s) are BIM-related educational content offered within the identified academic programme?",
  },
  {
    question_id: 1662404194408,
    es: "¿Cuántos módulos del programa académico identificado ofrecen contenidos educativos relacionados con BIM?",
    default:
      "How many modules within the identified academic programme offer BIM-related educational content?",
  },
  {
    question_id: 1662404194401,
    es: "¿Cómo se integran los contenidos relacionados con BIM en este programa educativo?",
    default:
      "How is BIM-related content infused into the educational programme?",
  },
  {
    question_id: 1662404194402,
    es: "¿Cómo se enseñan a los estudiantes los contenidos relacionados con BIM dentro de este programa?",
    default:
      "How are students taught BIM-related content within this programme?",
  },
  {
    question_id: 1662404194403,
    es: "¿Cuáles de los siguientes factores fomentaron la inclusión de contenidos relacionados con BIM en este programa?",
    default:
      "Which of the below factors encouraged the inclusion of BIM-related content within this programme?",
  },
  {
    question_id: 1662404194404,
    es: "¿Qué contenidos BIM relacionados con [[Captura y representación]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Capturing and Representing]] are taught as part of this programme?",
  },
  {
    question_id: 1665076969613,
    es: "¿Qué contenidos BIM relacionados con [[Planificación y diseño]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Planning and Designing]] are taught as part of this programme?",
  },
  {
    question_id: 1665076969614,
    es: "¿Qué contenidos BIM relacionados con [[Simulación y cuantificación]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Simulating and Quantifying]] are taught as part of this programme?",
  },
  {
    question_id: 1665080678817,
    es: "¿Qué contenidos BIM relacionados con [[Construcción y Fabricación]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Constructing and Fabricating]] are taught as part of this programme?",
  },
  {
    question_id: 1665080678815,
    es: "¿Qué contenidos BIM relacionados con [[Operación y mantenimiento]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Operating and Maintaining]] are taught as part of this programme?",
  },
  {
    question_id: 1665080678819,
    es: "¿Qué contenidos BIM relacionados con [[Interoperabilidad]] se imparten como parte de este programa?",
    default:
      "What BIM content related to [[Interoperability]] are taught as part of this programme?",
  },
  {
    question_id: 1665080678818,
    es: "¿Qué contenidos generales de BIM se imparten como parte de este programa?",
    default:
      "What general BIM contents are taught as part of this programme?",
  },
  {
    question_id: 1662404194405,
    es: "¿Cuál es el formato educativo utilizado para los contenidos relacionados con BIM dentro de su programa?",
    default:
      "What is the educational delivery format used for BIM-related content within your programme?",
  },
  {
    question_id: 1662404194409,
    es: "¿Qué tipos de recursos de aprendizaje en el campus relacionados con BIM están a disposición de los estudiantes en este programa?",
    default:
      "What types of BIM-related on-campus learning resources are available to students within this programme?",
  },
];

export const section2 = [
  {
    question_id: 1662416269541,
    es: "¿El programa identificado en el apartado anterior genera investigación relacionada con BIM?",
    default:
      "Does the programme identified in the previous section generate BIM-related research?",
  },
  {
    question_id: 1662416269548,
    es: "¿Qué tipos de resultados de investigación relacionados con BIM genera este programa?",
    default:
      "What types of BIM-related research deliverables are generated by this programme?",
  },
  {
    question_id: 1662416269554,
    es: "Identifique el repositorio o repositorios de acceso público para la investigación relacionada con BIM realizada por este programa:",
    default:
      "Please identify the publicly accessible repository(ies) for BIM-related research delivered by this programme:",
  },
];

export const section5 = [
  {
    question_id: 1662406986478,
    es: "¿Existen cursos breves de [[Formación BIM]] (por ejemplo, cursos de desarrollo profesional continuo) en su región?",
    default:
      "Are there short [[BIM Training]] courses (e.g., continuous professional development courses) available in your region?",
  },
  {
    question_id: 1662416260169,
    es: "¿Qué instituciones imparten estos cursos de [[Formación BIM]] en su región?",
    default:
      "Which institutions provide these [[BIM Training]] courses in your region?",
  },
  {
    question_id: 1662416269575,
    es: "¿Qué tipo de contenidos se imparten en los cursos breves de [[Formación BIM]]?",
    default:
      "What type of content is delivered in the short [[BIM Training]] courses?",
  },
  {
    question_id: 1662416269584,
    es: "¿Existen cursos cortos de [[Formación BIM]] acreditados/certificados por organismos de acreditación?",
    default:
      "Are there short [[BIM Training]] courses accredited/certified by accreditation bodies?",
  },
  {
    question_id: 1662416269547,
    es: "Por favor, identifique los organismos de acreditación que han certificado/acreditado esos cursos cortos de [[Formación BIM]]:",
    default:
      "Please identify the accreditation bodies that have certified/accredited those short [[BIM Training]] courses:",
  },
];

export const section6 = [
  {
    question_id: "1696216528318",
    es: "¿Existe alguna colaboración formal entre la academia, el gobierno y/o la industria con el fin de mejorar la [[Competencia BIM]]?",
    default:
      "Is there any formal collaboration between academia, government and/or industry for the purposes of improving [[BIM Competency]]?",
  },
  {
    question_id: "1696216897343",
    es: "¿Qué cubre esta colaboración formal entre la academia, el gobierno y/o la industria con respecto a la [[Competencia BIM]]?",
    default:
      "What does this formal collaboration between academia, government and/or industry cover with respect to [[BIM competency]]?",
  },
  {
    question_id: "1696217569183",
    es: "Por favor, identifique las partes incluidas en esta colaboración formal entre la academia, el gobierno y/o la industria que cubre la [[Competencia BIM]]:",
    default:
      "Please identify the parties included in this formal collaboration between academia, government and/or industry covering [[BIM competency]]:",
  },
  {
    question_id: "1696216665638",
    es: "Proporcione más información sobre los objetivos y resultados de la colaboración formal entre el mundo académico, el gobierno y/o la industria con el fin de mejorar la [[Competencia BIM]]:",
    default:
      "Please provide more information about the objectives and deliverables of the formal collaboration between academia, government and/or industry for the purposes of improving [[BIM competency]]:",
  },
];
