name: CI/CD
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: check out repository
        uses: actions/checkout@v4
